"""Initial schema

Revision ID: c5e94cc64564
Revises: 
Create Date: 2025-07-07 17:31:03.640450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e94cc64564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compost_piles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ext_id', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('greens', sa.Integer(), nullable=True),
    sa.Column('browns', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compost_piles_ext_id'), 'compost_piles', ['ext_id'], unique=False)
    op.create_index(op.f('ix_compost_piles_id'), 'compost_piles', ['id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('pile_id', sa.Integer(), nullable=True),
    sa.Column('fc_compost_operation_id', sa.String(), nullable=True),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pile_id'], ['compost_piles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_compost_piles_id'), table_name='compost_piles')
    op.drop_index(op.f('ix_compost_piles_ext_id'), table_name='compost_piles')
    op.drop_table('compost_piles')
    # ### end Alembic commands ###
